version: '3.8'
services:
  rest-service:
    image: rest-service
    container_name: rest-service
    ports:
      - "3030:${PORT}"
    depends_on:
      - rest-db
    env_file:
      - .env
    volumes:
      - ./index.ts:/app/index.ts
      - ./src:/app/src

  rest-db:
    image: postgres:16-alpine
    container_name: rest-postgres
    ports:
      - "5433:${POSTGRES_PORT}"
    env_file:
      - .env
    # volumes:
    #   - ./database/database-seed:/docker-entrypoint-initdb.d/database-seed.sql